language: java
dist: trusty
jdk:
- oraclejdk8
branches:
  only:
  - master
env:
  global:
  - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
  - CODECOV_TOKEN="7669b20c-ee7b-41eb-a385-ee6f238337a3"
script: ./build.sh